services:
  pg-database:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: ny_tax
    volumes:
      - ./ny_taxi_postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pg-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
    ports:
      - 8080:80
